import { TaskTemplate } from "@/domain/models";

export const seedTemplates: TaskTemplate[] = [
  {
    id: "template_walk_10_easy",
    title: "Walk 10 minutes",
    category: "walking",
    points: 2,
    frequency: { type: "weekly", target: 4 },
    difficulty: "easy",
    estimatedMinutes: 10,
    definitionOfDone: "Complete a 10-minute easy walk.",
    fallback: "Walk for 5 minutes.",
    blockers: ["no_time", "low_energy", "weather"],
    tags: ["exercise", "walking", "beginner"],
    packIds: ["beginner_week", "walking_focus", "low_motivation_week"]
  },
  {
    id: "template_cycle_8_easy",
    title: "Cycle 8 minutes easy pace",
    category: "cycling",
    points: 2,
    frequency: { type: "weekly", target: 3 },
    difficulty: "easy",
    estimatedMinutes: 8,
    definitionOfDone: "Complete 8 minutes on the exercise bike at a comfortable pace.",
    fallback: "Cycle for 5 minutes.",
    blockers: ["low_energy", "no_time", "boredom"],
    tags: ["exercise", "bike", "beginner"],
    packIds: ["beginner_week", "cycling_focus"]
  },
  {
    id: "template_water_target",
    title: "Hit water target",
    category: "water",
    points: 2,
    frequency: { type: "weekly", target: 5 },
    difficulty: "easy",
    estimatedMinutes: 1,
    definitionOfDone: "Reach the planned water target for the day.",
    fallback: "Drink one full glass of water.",
    blockers: ["forgot", "travel"],
    tags: ["hydration", "daily"],
    packIds: ["beginner_week", "water_focus"]
  },
  {
    id: "template_protein_anchor",
    title: "Add one protein anchor meal",
    category: "protein",
    points: 3,
    frequency: { type: "weekly", target: 5 },
    difficulty: "easy",
    estimatedMinutes: 15,
    definitionOfDone: "Include a clear protein source in one home-cooked meal.",
    fallback: "Add curd, eggs, paneer, dal, chicken, tofu, or sprouts to one meal.",
    blockers: ["no_prep", "low_appetite"],
    tags: ["nutrition", "protein", "home_food"],
    packIds: ["beginner_week", "protein_focus", "food_reset_week"]
  },
  {
    id: "template_home_food",
    title: "Choose home-cooked food",
    category: "home_food",
    points: 3,
    frequency: { type: "weekly", target: 5 },
    difficulty: "easy",
    estimatedMinutes: 20,
    definitionOfDone: "Eat a planned home-cooked meal instead of ordering impulsively.",
    fallback: "Assemble the simplest available home meal.",
    blockers: ["late_work", "cravings", "no_groceries"],
    tags: ["nutrition", "home_food"],
    packIds: ["beginner_week", "busy_work_week", "food_reset_week"]
  },
  {
    id: "template_fiber_plate",
    title: "Add fiber to one meal",
    category: "fiber",
    points: 2,
    frequency: { type: "weekly", target: 5 },
    difficulty: "easy",
    estimatedMinutes: 5,
    definitionOfDone: "Add vegetables, fruit, beans, or whole grains to one meal.",
    fallback: "Add one fruit or simple salad.",
    blockers: ["no_prep", "forgot"],
    tags: ["nutrition", "fiber"],
    packIds: ["food_reset_week"]
  },
  {
    id: "template_calorie_check",
    title: "Log a simple calorie estimate",
    category: "calories",
    points: 2,
    frequency: { type: "weekly", target: 5 },
    difficulty: "easy",
    estimatedMinutes: 5,
    definitionOfDone: "Record a reasonable calorie estimate for the day without chasing perfect accuracy.",
    fallback: "Write down the highest-calorie meal only.",
    blockers: ["forgot", "too_tedious", "eating_out"],
    tags: ["nutrition", "calories", "awareness"],
    packIds: ["food_reset_week", "busy_work_week", "plateau_reset"]
  },
  {
    id: "template_busy_walk_5",
    title: "Walk 5 minutes",
    category: "walking",
    points: 1,
    frequency: { type: "weekly", target: 5 },
    difficulty: "easy",
    estimatedMinutes: 5,
    definitionOfDone: "Complete a 5-minute walk anywhere.",
    fallback: "Do one slow lap around the house.",
    blockers: ["no_time", "low_energy", "weather"],
    tags: ["exercise", "walking", "fallback"],
    packIds: ["low_motivation_week", "busy_work_week", "recovery_week"]
  },
  {
    id: "template_cycle_15_easy",
    title: "Cycle 15 minutes easy pace",
    category: "cycling",
    points: 3,
    frequency: { type: "weekly", target: 3 },
    difficulty: "easy",
    estimatedMinutes: 15,
    definitionOfDone: "Complete 15 minutes on the exercise bike at a comfortable pace.",
    fallback: "Cycle for 5 minutes.",
    blockers: ["low_energy", "no_time", "boredom"],
    tags: ["exercise", "bike", "beginner"],
    packIds: ["cycling_focus", "build_week"]
  },
  {
    id: "template_sleep_window",
    title: "Protect sleep window",
    category: "sleep",
    points: 2,
    frequency: { type: "weekly", target: 4 },
    difficulty: "easy",
    estimatedMinutes: 10,
    definitionOfDone: "Start winding down at the planned time and avoid adding new work late.",
    fallback: "Put the phone away 10 minutes earlier than usual.",
    blockers: ["late_work", "screen_time", "stress"],
    tags: ["sleep", "recovery"],
    packIds: ["recovery_week", "low_motivation_week"]
  },
  {
    id: "template_restart_note",
    title: "Write one restart note",
    category: "mindset",
    points: 1,
    frequency: { type: "weekly", target: 3 },
    difficulty: "easy",
    estimatedMinutes: 3,
    definitionOfDone: "Write one sentence about the next smallest useful action.",
    fallback: "Say the next action out loud.",
    blockers: ["discouraged", "overthinking"],
    tags: ["mindset", "restart"],
    packIds: ["low_motivation_week", "recovery_week"]
  },
  {
    id: "template_recovery_stretch",
    title: "Stretch 3 minutes",
    category: "recovery",
    points: 1,
    frequency: { type: "weekly", target: 4 },
    difficulty: "easy",
    estimatedMinutes: 3,
    definitionOfDone: "Do gentle stretching or mobility for 3 minutes.",
    fallback: "Take five slow breaths and loosen shoulders.",
    blockers: ["forgot", "low_energy"],
    tags: ["recovery", "mobility", "fallback"],
    packIds: ["recovery_week", "low_motivation_week"]
  },
  {
    id: "template_plateau_review",
    title: "Review adherence without judgment",
    category: "mindset",
    points: 2,
    frequency: { type: "weekly", target: 1 },
    difficulty: "easy",
    estimatedMinutes: 10,
    definitionOfDone: "Review calories, protein, water, and sodium patterns for the week as data.",
    fallback: "Pick one habit to make easier tomorrow.",
    blockers: ["discouraged", "scale_stress"],
    tags: ["plateau", "review", "mindset"],
    packIds: ["plateau_reset"]
  }
];
